- crates/chat-cli/src/auth/builder_id.rs
- crates/fig_auth/src/builder_id.rs
A mirror of https://github.com/aws/amazon-q-developer-cli/pull/1929 to keep the two repos in sync. 
> fix: add stalled stream protection config to SSO client (#1929)

- crates/semantic_search_client/tests/test_add_context_from_path.rs
Makes sure tests won't invoke real embeddings. Fixes issue in CI pipeline for MAC OS env.
> Fix: Fixes semantic crate tests

- crates/chat-cli/src/cli/chat/tools/fs_read.rs
Removal of redundant output during fs_read tool invocation.
Before: 
After:
> Fix: broken format for fs read tool use description

- Cargo.lock
- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/cli/chat/mcp.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/platform/fs/mod.rs
- crates/chat-cli/src/platform/fs/unix.rs
- crates/chat-cli/src/platform/fs/windows.rs
This PR introduces Windows-specific path handling functionality and includes code cleanup to address Clippy
warnings.
• **Windows Path Handling**: Added Windows-specific path appending functionality to ensure proper path
construction on Windows systems
• Implemented automatic path normalization for Windows during test runtime
• Addresses the challenge where Unix-style paths aren't properly recognized on Windows systems
• Eliminates the need to maintain separate test paths for different operating systems
• **Code Cleanup**: Fixed Clippy warnings to improve code quality and maintainability
Rust's path handling is OS-dependent, creating challenges for cross-platform testing. On Windows, Unix-style
paths (with forward slashes) aren't properly recognized - for example, a leading / isn't …
> feat(windows): refactor filesystem handling to support windows

- crates/chat-cli/src/cli/chat/mod.rs
Users report:
When Q is streaming a large block of text, ctrl-c no longer interrupts the output.
There exists a `handle_response` function, which is polled along side the sigint handler:
```rust
ChatState::HandleResponseStream(response) => tokio::select! {
res = self.handle_response(database, telemetry, response) => res,
Ok(_) = ctrl_c_stream => Err(ChatError::Interrupted { tool_uses: None })
},
```
But `handle_response` never yields when it processes a large block content when it processes a large block of text, due to the following loop:
```rust
loop {
let input = Partial::new(&buf[offset..]);
match interpret_markdown(input, &mut self.output, &mut state) {
Ok(parsed) => {
offset += parsed.offset_from(&input);
self.output.flush()?; …
```
> Fix: sigint not caught during parsing of large block of text

- crates/chat-cli/src/mcp_client/client.rs
https://github.com/aws/amazon-q-developer-cli/issues/1857
Adds tilde expansion to mcp start command.
> Fix: mcp start command not respecting tilde

- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/mcp_client/transport/stdio.rs
Users report: 
- _Sometimes_ q cli will run hot, taking up high CPU usage.
- Observed along with this high CPU usage is a failure for some MCP servers to load. Though this observation is only made by one user. And it is not made certain due to a lack of consistent reproducible examples. 
- The reporting users did produce sample logs, but the references are mangled and only shows the llvm optimized hash. 
_One of_ the potential causes for the hot loop is in the background tasks spawned to listen for incoming messages from the server. The fix here is to condition the loop in such a way that they end once the child process no longer exists.  
This is confirmed by killing all Q CLI's child processes, and subsequently we can observe that the CPU usage for q chat sky …
> Fix: mcp client background task entering a hot loop on child process crash

- crates/chat-cli/src/api_client/clients/client.rs
- crates/chat-cli/src/api_client/clients/streaming_client.rs
- crates/chat-cli/src/api_client/consts.rs
- crates/chat-cli/src/api_client/error.rs
- crates/chat-cli/src/auth/builder_id.rs
- crates/chat-cli/src/cli/chat/command.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/q_cli/src/cli/user.rs
- Add better message to indicate when the user has reached their monthly query limit.
- Add new command `/subscribe` to initiate a subscription flow to paid usage for builder ID users
- Includes option `--manage` to open the subscription page on console where to user can cancel if they want.
- IDC users cannot use this flow
> feat: q builder id pro subscription flow

- crates/q_cli/src/cli/mod.rs
*Issue #, if available:* #168
- Updating the qchat launch logic to fallback to a global `qchat` on the path if it is not found in `/usr/bin` or `~/.local/bin`
> fix: qchat launch logic on linux to fallback to a global qchat

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to `1.12.0` and adding `feed.json` entries.
> chore: bump version to 1.12.0

- crates/chat-cli/src/telemetry/mod.rs
Previously, when `TelemetryThread::finish` is called, it awaits for the channel to close out, with a timeout of 1s.
This always times out because TelemetryThread is used in several background tasks. Because these background tasks own the mpsc senders, the channel never closes. 
This PR changes this so that clones of the `TelemetryThread` creates weak references. So that when the main sender is dropped, the channel closes.
> Fix: telemetry thread clone vends strong sender causing delay

- crates/chat-cli/src/cli/chat/mod.rs
https://github.com/aws/amazon-q-developer-cli/issues/1764
Add instructions on how to invoke `/prompts` and tip
> chore: Add instructions on how to invoke `/prompts`

- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/token_counter.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/util/mod.rs
https://github.com/aws/amazon-q-developer-cli/issues/2044
1.` /compact` would fail with ToolUse has no corresponding tool spec.
Steps to reproduce:
Use fs_read tool to read an image via Q CLI
Send a random message to ensure a conversation history is established
Run /compact
❌ You’ll see a validation error due to the missing tool spec in the summary request
2. The `/usage` command does not account for token space used by tool specs from configured MCP servers, which could be large.
This PR includes two related improvements:
1. `/compact` always includes tool specs (and cancels dangling tool-uses)
- Add tools field in `UserInputMessageContext` when generating summary request.
2. `/usage` now counts tool specs accurately (built in + mcp tools)
- Uses …
> fix: `/compact` validation error: missing tool specs

- crates/chat-cli/src/cli/chat/mod.rs
Description of changes: User is now prompted for reason upon denying tool use. Allows model to gather more information rather than just 'n.' 
> Fix: prompt denial reason upon tool use denial

- crates/chat-cli/src/cli/chat/consts.rs
- Currently tool uses can overflow the context window with a single message, causing `/compact` to fail in the scenario where there is only a single large tool use in the conversation history. Therefore, reducing the maximum size to `400_000` characters instead
- Sonnet 3.5/3.7/4.0 all have a size of 200k tokens, so 400k characters should reduce the number of times we hit this edge case - https://docs.anthropic.com/en/docs/about-claude/models/overview#model-comparison-table
> fix: reduce maximum tool use response size to 400,000

- crates/chat-cli/src/cli/chat/tools/fs_write.rs
*Issue #, if available:* https://github.com/aws/amazon-q-developer-cli/issues/1932
- Handles bug where `~` in path would cause fs_write issue:
```
Amazon Q is having trouble responding right now:
0: failed to print tool, `fs_write`: No such file or directory (os error 2)
Location:
crates/chat-cli/src/cli/chat/mod.rs:1221
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
Before:
After:
> fix: update fs_write tool for relative and absolute paths

- crates/chat-cli/src/cli/chat/cli/context.rs
A bool field without additional attributes is treated as a positional argument by default, but clap is trying to apply SetTrue action to it (which is for flags).
> Fix: not being able to run slash context subcommand

- crates/chat-cli/src/cli/chat/tools/fs_write.rs
**### After:**
This PR restores the original behavior of printing both relative and absolute paths after using the `fs_write` tool  in [#256](https://github.com/aws/amazon-q-developer-cli-autocomplete/pull/256), which was lost during the slash command refactor
Let me know if we want to gate this behind a flag or setting.
> fix: restore relative and absolute path printing in `fs_write` after slash command refactor

- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
Currently if you call `--trust-tools` with tools that will be vended by MCP servers, the configuration doesn't take effect if the server takes too long to start.
Reproduction steps:
1. Run `q chat --trust-tools=<tool>` (e.g. `clear_thought___sequentialthinking`)
2. Wait for the MCP server to start up
3. Run `/tools` to check trust status
4. Validate the (incorrectly untrusted) trust status by asking Q to run the tool for some trivial purpose.
Port of https://github.com/aws/amazon-q-developer-cli/pull/2039 to this older repository, since it's unclear which one of them is currently the site of active development.
EDIT: FYI, this code is largely Q-CLI written, as I'm not an experienced Rust coder. I've tried to ensure it matches the expected …
> Fix: Allow --trust-tools to work on MCP servers

- crates/chat-cli/src/mcp_client/client.rs
> Fix: child process spawned for mcp no inheriting env vars from parent

- crates/q_cli/src/util/mod.rs
- Adding support for Sigv4 with the `q` binary when spawning the `qchat` binary by assuming the user is logged in if the `AMAZON_Q_SIGV4` env var is set. This is the same env var used in the `qchat` binary for using sigv4.
- CloudShell checking is deprecated and not used.
> fix: add login check for sigv4 chat support

- crates/chat-cli/src/api_client/mod.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/telemetry/mod.rs
- Printing the banner and other various text to stderr in non-interactive mode, since this is machine-readable output and users should not be depending on this in non-interactive use cases.
- Removing the cw telemetry client if sigv4 auth is being used, since cw telemetry requires bearer token auth
> fix: remove cw telemetry client for sigv4, revert skipping banner printing to stderr in noninteractive mode

- crates/chat-cli/src/cli/chat/mod.rs
- Resolve the stream parsing regression to go back to the previous behavior of continually printing the assistant response rather than line-buffered printing
- Changing the message we send to the model when the user enters 'n' for a tool use deny to something more meaningful.
Example chat flow with 'n':
> fix: stream responses correctly

- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/mod.rs
- feed.json
- Removing the `/knowledge` subcommand from the feed and help, since it needs more polish before any public advertising.
- Removing the "accept completions" tip, reverting back to the same format we had before.
- Reducing the length of the printed tips in `/help` to support smaller terminal sizes, since at the moment we don't properly implement word wrapping.
Updated `/help` visual:
> chore: hide /knowledge command, reduce tips width

- crates/chat-cli/src/cli/chat/cli/prompts.rs
- crates/chat-cli/src/cli/chat/mod.rs
- Removing an unnecessary moveup command when printing an assistant response
- Resolving a panic issue with large prompt names in the `/prompts` command
`/prompts` output examples:
> fix: newline printing on requests, panic with /prompts

- crates/chat-cli/src/cli/chat/util/mod.rs
The emacs eat terminal (https://codeberg.org/akib/emacs-eat) handles
beeps fine, and the beep feature only works for allowlisted terminals.
> fix: Add bell support for eat terminal

- build-scripts/signing.py
- Updating the build script to specify the aws region when loading secrets. This is fine in CI due to a version difference with the installed aws CLI in CI, but fails when ran locally on a modern aws CLI version.
> fix: build script to specify the aws region when loading secrets

- crates/chat-cli/src/cli/chat/cli/persist.rs
When users run /load to restore a conversation, we should repopulate the ToolManager, since it is not serialized during /save.
> fix: restore tool manager for the current session when /load conversation

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to v1.12.4 and adding feed.json entries
> chore: bump version to 1.12.4

- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/message.rs
- crates/chat-cli/src/cli/chat/mod.rs
- feed.json
Addressing issues not caught by #402 
- Moving the conversation invariant code into a shared function across the normal request flow and the compact flow.
- Adding a new conversation invariant check for when the next user message contains tool use results, but the last assistant message does not contain a corresponding tool use. This is encountered in the current `/compact` implementation as an unhandled edge case
- Not sending the complete tool spec as part of the compact request
- Including the current summary as context for the compact request, if available.
- Changing the compaction algorithm to instead only truncate if `history.len() <= 2` (ie, the history includes at most 2 user/assistant message pairs). This is done because it's almost always the case that …
> fix: more issues with /compact

- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/database/settings.rs
Adding boolean setting for history hints. If the settings is not set, it's taken as false by default.
```
q settings chat.enableHistoryHints true
```
> feat: Adding boolean setting for history hints

- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/cli/chat/tools/use_aws.rs
- crates/chat-cli/src/cli/mod.rs
- crates/chat-cli/src/telemetry/core.rs
- crates/chat-cli/src/telemetry/definitions.rs
- crates/chat-cli/src/telemetry/mod.rs
- crates/chat-cli/src/util/consts.rs
- crates/chat-cli/telemetry_definitions.json
NA
1. New metric referring the client application using the Q CLI
- Use `Q_CLI_CLIENT_APPLICATION` environment variable to set this field
- Telemetry events supporting this new metric:
* ChatAddedMessage
* CliSubcommandExecuted
* ToolUseSuggested
* McpServerInit
* MessageResponseError
2. Additional information about the tool being used
- Example for `use_aws` tool: `aws_service_name` and `aws_operation_name`
- Any tool can leverage this metric in future if needed
> feat(telemetry): add client application and additional info from tool

- crates/chat-cli/src/cli/chat/tools/execute/mod.rs
- Adding `-ok` checking for readonly checks on `find`, since it can be used to execute arbitrary code. Example: `echo y | find . -type f -maxdepth 1 -okdir open -a Calculator {} +`
- Adding `-P` for grep, since perl regexp can have similar code execution with `(?{..})` syntax. This doesn't seem to be implemented with grep, but since it's possible with perl regexp's and is marked as experimental in `man grep`, adding it here for safety.
> fix: execute bash perms for potential unwanted execution

- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/cli/chat/cli/hooks.rs
- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- Updating the conversation hooks to be consistent across user messages and tool use results, which enables prompt caching by the backend. Now, we will *always* include conversation start hooks in every request (other than `/compact`).
- Adding `preserve_order` to `serde_json` since the ordering for maps is otherwise nondeterministic. This is required for prompt caching (reasoning: large tool specs -> higher chance for nondeterministic key reordering across requests -> cache misses)
> fix: formatting hooks to enable correct caching with the API

- crates/chat-cli/src/cli/chat/mod.rs
Internal issue. Summary as below: 
The Amazon Q CLI has incorrectly escalated permissions for the execute_bash tool without my consent, allowing it to execute a shell command without ever having been granted approval, which was not the expected or desired behavior.
Example: 
```bash
> /tools
Tool                                                    Permission
▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔▔Built-in:
- execute_bash                                          * trust read-only commands
- fs_read                                               * trusted
- fs_write                                              * not trusted
- report_issue                                          * trusted
- use_aws …
```
> fixes inability to untrust read only tools

- crates/q_cli/src/cli/mod.rs
This reverts commit 4572eec47624f3fe6aecdb4782791d5b2832631b.
#443 originally reverted #431 due to a release, so this PR is adding it back.
> Revert "Revert "feat(agent): adds root command for chat's agent root command (#431)" (#443)"

- feed.json
- Removing feed item that won't be in the next release.
> chore: update feed to remove toolSettings fix

- Cargo.lock
- Cargo.toml
- feed.json
> chore: version bump

- Cargo.lock
- Cargo.toml
- feed.json
- Update version from 1.16.3 to 1.17.0 in Cargo.toml and Info.plist files
- Add new release entry for version 1.17.0 in feed.json with:
- SSE support for MCP
- /reply command
- Experimental checkpointing functionality
- Context usage percentage indicator
- Custom prompts support
- Various MCP fixes and improvements
🤖 Assisted by Amazon Q Developer
> feat: bump version to 1.17.0 and update feed.json
