aws/amazon-q-developer-cli-autocomplete

- crates/chat-cli/src/cli/chat/tool_manager.rs
- feed.json
> removes unqualified tools from tool list

- crates/chat-cli/src/cli/chat/mod.rs
> chore: limit tips to model selection for the current release

- crates/chat-cli/src/cli/chat/parser.rs
- Updating message id to be a uuid since it is required by downstream dependencies.
> chore: update message id to be a uuid

- build-config/buildspec-linux-ubuntu.yml
> fix: fix build script

- build-config/buildspec-macos_aarch64.yml
> chore: update ssm command for macos build config

- .gitattributes
- .github/workflows/rust.yml
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/platform/fs/windows.rs
- crates/chat-cli/src/platform/mod.rs
- crates/chat-cli/src/util/directories.rs
This PR adds comprehensive Windows support to the Amazon Q Developer CLI,
focusing on fixing test failures and ensuring proper CI integration.
* Added Windows-specific CI workflows for testing and linting the chat_cli crate
* Created .gitattributes file to ensure consistent line endings across platforms (LF for Rust files, Cargo files, and .gitignore)
* Fixed path handling in Windows filesystem operations:
* Implemented proper case-insensitive path comparison for Windows
* Added Windows-specific symlink creation logic that differentiates between files and directories
* Enhanced path joining and normalization to handle Windows path separators correctly
* Fixed remaining test failures on Windows by:
* Updating directory path handling to use the correct environment variables (USERPROFILE …
> feat(windows): Implement CI

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to 1.12.1
> chore: bump version to 1.12.1

- crates/chat-cli/src/cli/chat/mod.rs
This PR removes the `DEFAULT_MODEL_ID` constant and replaces it with a runtime `default_model_id(database)` function.
The function inspects the auth profile's region to determine whether to return S4 as default or fall back to the S3.7 as default.
> feat: dynamic default model resolution based on region

- feed.json
- Adding missing feed.json items
> chore: add missing feed items

- crates/chat-cli/src/cli/chat/mod.rs
> fix: revise the default model logic 

- .typos.toml
- Fixing typos-cli lint error for #264 
> chore: fix typos lint error

- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/mcp.rs
- crates/chat-cli/src/cli/mod.rs
> fix the unit test

- crates/chat-cli/src/cli/chat/mod.rs
- Updating the help error description so that we are printing a "/", and proper arguments.
- There is a redundant "For more information..." line (since we also include `-h / --help` in the printed options) which we might want to remove, but I left as is for now.
Some example screenshots:
> fix: show proper error messages on command help

- crates/chat-cli/src/cli/chat/cli/context.rs
- crates/chat-cli/src/cli/chat/cli/tools.rs
- crates/chat-cli/src/cli/chat/mod.rs
- Adding fixes for non-interactive mode to match the previous behavior (skip printing header, exit with an error on a tool use approval without --trust-all-tools)
- Minor fixes for missing required args in some slash commands
> fix: various bugs with chat

- crates/chat-cli/src/cli/chat/mod.rs
- Print only the help text for the subcommand that failed, rather than the help text for the entire command.
Example:
> fix: print only the subcommand help on slash command errors

- crates/chat-cli/src/cli/chat/cli/tools.rs
- crates/chat-cli/src/cli/chat/mod.rs
- Fixed all formatting new line issues with /tools
- Make sure ctrl_c error reason prints on new line
> Format bug bash

- crates/chat-cli/src/cli/chat/tools/execute/unix.rs
> feat: add support for ZSH using an envvar

- crates/chat-cli/src/auth/builder_id.rs
- crates/chat-cli/src/auth/consts.rs
- crates/chat-cli/src/cli/chat/cli/model.rs
- crates/chat-cli/src/cli/chat/mod.rs
> chore: update default model to sonnet 3.7 for internal user

- Cargo.lock
- Cargo.toml
- feed-schema.json
- feed.json
- Bumping version to `1.12.3` and adding feed.json changes
> chore: bump version to 1.12.3

- build-config/buildspec-linux-minimal.yml
- build-config/buildspec-linux-ubuntu.yml
- build-scripts/build-macos.sh
- build-scripts/build.py
- build-scripts/main.py
- Adding the required build script changes to bundle the `qchat` from a separate account instead.
> feat: update build to bundle from qchat pipeline

- crates/chat-cli/src/auth/builder_id.rs
- crates/fig_auth/src/builder_id.rs
- crates/q_cli/src/cli/mod.rs
- Adding extra debug statements to help root cause issues with authentication
> chore: add debug statements around auth checking

- feed.json
- Adding sigv4 support to the feed.json
> chore: add sigv4 to feed

- crates/q_cli/src/cli/mod.rs
> feat(agent): adds root command for chat's agent root command

- crates/q_cli/src/cli/mod.rs
This reverts commit affacdb1ea83b94b967af6c971c8ab596c5742b5. #431 
- Required for creating a release
> Revert "feat(agent): adds root command for chat's agent root command (#431)"

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to 1.12.6
> chore: bump version to 1.12.6

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to 1.12.7
> chore: bump version to 1.12.7

- Cargo.lock
- Cargo.toml
- feed.json
> chore: bump version to 1.13.2

- feed.json
> chore: create build

- .gitattributes
- models/LICENSE
- models/NOTICE
- models/README.md
- models/all-MiniLM-L6-v2.zip
- Configure Git LFS to track models/*.zip files
- Add semantic-models.zip (83MB) containing all-MiniLM-L6-v2 model
- Include Apache 2.0 LICENSE for proper license compliance
- Add NOTICE file with copyright attribution
- Add README.md with usage instructions and license information
This enables offline semantic search functionality while maintaining repository performance through Git LFS.
Restructure models with individual zip files per model
> Add semantic search models with Git LFS

- feed.json
> chore: update feed entries

- feed.json
> chore: remove knowledge from feed

- feed.json
> chore: update feed to add back knowledge

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to 1.14.0 and adding `feed.json` changes
> chore: bump version to 1.14.0

- Cargo.lock
- Cargo.toml
- feed.json
> chore: bump version to 1.15.0

- feed.json
> Chore: change release date to trigger a build

- crates/fig_settings/src/sqlite/mod.rs
Some entries in DB won't have expected format by UI, this ignores this entries to avoid any compatibility issue.
> [fix] Ignores entries failing parsing

- feed.json
- Adding a feed.json entry for `1.16.1`
> chore: add feed.json entry

- Cargo.lock
- Cargo.toml
- feed.json
> chore: version bumps and updates feed
